require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MarinesController do

  # This should return the minimal set of attributes required to create a valid
  # Marine. As you add validations to Marine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MarinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all marines as @marines" do
      marine = Marine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:marines).should eq([marine])
    end
  end

  describe "GET show" do
    it "assigns the requested marine as @marine" do
      marine = Marine.create! valid_attributes
      get :show, {:id => marine.to_param}, valid_session
      assigns(:marine).should eq(marine)
    end
  end

  describe "GET new" do
    it "assigns a new marine as @marine" do
      get :new, {}, valid_session
      assigns(:marine).should be_a_new(Marine)
    end
  end

  describe "GET edit" do
    it "assigns the requested marine as @marine" do
      marine = Marine.create! valid_attributes
      get :edit, {:id => marine.to_param}, valid_session
      assigns(:marine).should eq(marine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Marine" do
        expect {
          post :create, {:marine => valid_attributes}, valid_session
        }.to change(Marine, :count).by(1)
      end

      it "assigns a newly created marine as @marine" do
        post :create, {:marine => valid_attributes}, valid_session
        assigns(:marine).should be_a(Marine)
        assigns(:marine).should be_persisted
      end

      it "redirects to the created marine" do
        post :create, {:marine => valid_attributes}, valid_session
        response.should redirect_to(Marine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved marine as @marine" do
        # Trigger the behavior that occurs when invalid params are submitted
        Marine.any_instance.stub(:save).and_return(false)
        post :create, {:marine => {  }}, valid_session
        assigns(:marine).should be_a_new(Marine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Marine.any_instance.stub(:save).and_return(false)
        post :create, {:marine => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested marine" do
        marine = Marine.create! valid_attributes
        # Assuming there are no other marines in the database, this
        # specifies that the Marine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Marine.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => marine.to_param, :marine => { "these" => "params" }}, valid_session
      end

      it "assigns the requested marine as @marine" do
        marine = Marine.create! valid_attributes
        put :update, {:id => marine.to_param, :marine => valid_attributes}, valid_session
        assigns(:marine).should eq(marine)
      end

      it "redirects to the marine" do
        marine = Marine.create! valid_attributes
        put :update, {:id => marine.to_param, :marine => valid_attributes}, valid_session
        response.should redirect_to(marine)
      end
    end

    describe "with invalid params" do
      it "assigns the marine as @marine" do
        marine = Marine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Marine.any_instance.stub(:save).and_return(false)
        put :update, {:id => marine.to_param, :marine => {  }}, valid_session
        assigns(:marine).should eq(marine)
      end

      it "re-renders the 'edit' template" do
        marine = Marine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Marine.any_instance.stub(:save).and_return(false)
        put :update, {:id => marine.to_param, :marine => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested marine" do
      marine = Marine.create! valid_attributes
      expect {
        delete :destroy, {:id => marine.to_param}, valid_session
      }.to change(Marine, :count).by(-1)
    end

    it "redirects to the marines list" do
      marine = Marine.create! valid_attributes
      delete :destroy, {:id => marine.to_param}, valid_session
      response.should redirect_to(marines_url)
    end
  end

end
