require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TerrestrialsController do

  # This should return the minimal set of attributes required to create a valid
  # Terrestrial. As you add validations to Terrestrial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TerrestrialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all terrestrials as @terrestrials" do
      terrestrial = Terrestrial.create! valid_attributes
      get :index, {}, valid_session
      assigns(:terrestrials).should eq([terrestrial])
    end
  end

  describe "GET show" do
    it "assigns the requested terrestrial as @terrestrial" do
      terrestrial = Terrestrial.create! valid_attributes
      get :show, {:id => terrestrial.to_param}, valid_session
      assigns(:terrestrial).should eq(terrestrial)
    end
  end

  describe "GET new" do
    it "assigns a new terrestrial as @terrestrial" do
      get :new, {}, valid_session
      assigns(:terrestrial).should be_a_new(Terrestrial)
    end
  end

  describe "GET edit" do
    it "assigns the requested terrestrial as @terrestrial" do
      terrestrial = Terrestrial.create! valid_attributes
      get :edit, {:id => terrestrial.to_param}, valid_session
      assigns(:terrestrial).should eq(terrestrial)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Terrestrial" do
        expect {
          post :create, {:terrestrial => valid_attributes}, valid_session
        }.to change(Terrestrial, :count).by(1)
      end

      it "assigns a newly created terrestrial as @terrestrial" do
        post :create, {:terrestrial => valid_attributes}, valid_session
        assigns(:terrestrial).should be_a(Terrestrial)
        assigns(:terrestrial).should be_persisted
      end

      it "redirects to the created terrestrial" do
        post :create, {:terrestrial => valid_attributes}, valid_session
        response.should redirect_to(Terrestrial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved terrestrial as @terrestrial" do
        # Trigger the behavior that occurs when invalid params are submitted
        Terrestrial.any_instance.stub(:save).and_return(false)
        post :create, {:terrestrial => {  }}, valid_session
        assigns(:terrestrial).should be_a_new(Terrestrial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Terrestrial.any_instance.stub(:save).and_return(false)
        post :create, {:terrestrial => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested terrestrial" do
        terrestrial = Terrestrial.create! valid_attributes
        # Assuming there are no other terrestrials in the database, this
        # specifies that the Terrestrial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Terrestrial.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => terrestrial.to_param, :terrestrial => { "these" => "params" }}, valid_session
      end

      it "assigns the requested terrestrial as @terrestrial" do
        terrestrial = Terrestrial.create! valid_attributes
        put :update, {:id => terrestrial.to_param, :terrestrial => valid_attributes}, valid_session
        assigns(:terrestrial).should eq(terrestrial)
      end

      it "redirects to the terrestrial" do
        terrestrial = Terrestrial.create! valid_attributes
        put :update, {:id => terrestrial.to_param, :terrestrial => valid_attributes}, valid_session
        response.should redirect_to(terrestrial)
      end
    end

    describe "with invalid params" do
      it "assigns the terrestrial as @terrestrial" do
        terrestrial = Terrestrial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Terrestrial.any_instance.stub(:save).and_return(false)
        put :update, {:id => terrestrial.to_param, :terrestrial => {  }}, valid_session
        assigns(:terrestrial).should eq(terrestrial)
      end

      it "re-renders the 'edit' template" do
        terrestrial = Terrestrial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Terrestrial.any_instance.stub(:save).and_return(false)
        put :update, {:id => terrestrial.to_param, :terrestrial => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested terrestrial" do
      terrestrial = Terrestrial.create! valid_attributes
      expect {
        delete :destroy, {:id => terrestrial.to_param}, valid_session
      }.to change(Terrestrial, :count).by(-1)
    end

    it "redirects to the terrestrials list" do
      terrestrial = Terrestrial.create! valid_attributes
      delete :destroy, {:id => terrestrial.to_param}, valid_session
      response.should redirect_to(terrestrials_url)
    end
  end

end
